	var QCMS = [
		/* --- game 1 --- */
		[

		'<img class="img_400x400_'+thisDeviceType+'" src="img/4-méthylhexan-1-ol.png"><br>',
				"4-méthylhexan-1-ol",
				"3-méthylpent-2-énal",
				"1,3-diméthylbenzène",
				"propan-2-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/2-méthyloctan-1-ol.png"><br>',
				"2-méthyloctan-1-ol",
				"pent-3-èn-2-one",
				"acide 3-oxobutanoïque",
				"4-méthylpent-2-yne",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/but-1-yne.png"><br>',
				"but-1-yne",
				"3-méthylbutanal",
				"acide 3-formylbutanoïque",
				"1-éthyl-3-méthylcyclopentane",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/cyclohexane.png"><br>',
				"cyclohexane",
				"3-méthylbutanal",
				"acide propanoïque",
				"but-1-yne",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/éthanal.png"><br>',
				"éthanal",
				"1-éthyl-3-méthylcyclopentane",
				"1,2-diméthylcyclohex-1-ène",
				"cyclohexène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 3-formyl-2-oxobutanoïque.png"><br>',
				"acide 3-formyl-2-oxobutanoïque",
				"but-1-yne",
				"1,4-diméthylbenzène",
				"acide 5-chloro-2-formyl-4-oxohex-2-énoïque",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/3-méthylnonane.png"><br>',
				"3-méthylnonane",
				"acide 3-formyl-2-oxobutanoïque",
				"éthanol",
				"2,4,6-triméthyloctan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/4-méthyloctan-1-ol.png"><br>',
				"4-méthyloctan-1-ol",
				"pent-3-èn-2-one",
				"cyclopentène",
				"4-méthylpentan-2-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/4-méthylhex-5-èn-3-ol.png"><br>',
				"4-méthylhex-5-èn-3-ol",
				"3-méthylbutanal",
				"but-1-yne",
				"3-méthylpent-2-énal",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/1-éthyl-3-méthylcyclopentane.png"><br>',
				"1-éthyl-3-méthylcyclopentane",
				"3-bromohexane",
				"acide 2-éthyl-3-méthyl-4-oxopent-2-énoïque",
				"4-méthyloctan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/3-méthylpent-2-énal.png"><br>',
				"3-méthylpent-2-énal",
				"4-méthylhexan-1-ol",
				"acide 3-méthylbutanoïque",
				"pent-3-èn-2-one",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/pent-3-èn-2-one.png"><br>',
				"pent-3-èn-2-one",
				"propan-2-ol",
				"3-méthylnonane",
				"éthanal",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/3-bromohexane.png"><br>',
				"3-bromohexane",
				"acide 3-méthylbutanoïque",
				"1-éthyl-2-méthylbenzène",
				"acide pent-2-énoïque",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/2-chloropentane.png"><br>',
				"2-chloropentane",
				"cyclohexène",
				"acide 3-formyl-2-oxobutanoïque",
				"1-éthyl-2-méthylbenzène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/cyclohexène.png"><br>',
				"cyclohexène",
				"cyclohexane",
				"2-méthyloctan-1-ol",
				"4-méthylhexan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/4-méthylpent-2-yne.png"><br>',
				"4-méthylpent-2-yne",
				"acide 2-bromo-3-hydroxy-5-méthyl-4-oxohex-2-énoïque",
				"1,2-diméthylbenzène",
				"4-méthylhex-5-èn-3-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/cyclopentène.png"><br>',
				"cyclopentène",
				"4-méthylhex-5-èn-3-ol",
				"1,3-diméthylbenzène",
				"acide 3-méthylbutanoïque",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 2-éthyl-3-méthyl-4-oxopent-2-énoïque.png"><br>',
				"acide 2-éthyl-3-méthyl-4-oxopent-2-énoïque",
				"3-méthylpent-2-énal",
				"but-1-yne",
				"3-bromohexane",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/3-méthylbutanal.png"><br>',
				"3-méthylbutanal",
				"3-bromohexane",
				"acide propanoïque",
				"2-méthylpropan-2-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/1,2-diméthylcyclohex-1-ène.png"><br>',
				"1,2-diméthylcyclohex-1-ène",
				"cyclohexane",
				"acide 3-méthylbutanoïque",
				"2,4,6-triméthyloctan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 3-oxobutanoïque.png"><br>',
				"acide 3-oxobutanoïque",
				"éthanol",
				"1-éthyl-3-méthylcyclopentane",
				"3-bromohexane",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/1,2-diméthylbenzène.png"><br>',
				"1,2-diméthylbenzène",
				"acide 3-formyl-2-oxobutanoïque",
				"acide 3-méthylbutanoïque",
				"but-1-yne",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 5-chloro-2-formyl-4-oxohex-2-énoïque.png"><br>',
				"acide 5-chloro-2-formyl-4-oxohex-2-énoïque",
				"acide 2-bromo-3-hydroxy-5-méthyl-4-oxohex-2-énoïque",
				"propan-2-ol",
				"4-méthylpent-2-yne",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/2-éthyl-5-oxohexanal.png"><br>',
				"2-éthyl-5-oxohexanal",
				"4-méthylpent-2-yne",
				"acide propanoïque",
				"acide 3-formyl-2-oxobutanoïque",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/3-éthyl-3-méthylpenta-1,4-diène.png"><br>',
				"3-éthyl-3-méthylpenta-1,4-diène",
				"propan-2-ol",
				"acide 3-formyl-2-oxobutanoïque",
				"4-méthylhexan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/1,3-diméthylbenzène.png"><br>',
				"1,3-diméthylbenzène",
				"1,2-diméthylbenzène",
				"2-chloropentane",
				"3-éthyl-3-méthylpenta-1,4-diène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/1-éthyl-2-méthylbenzène.png"><br>',
				"1-éthyl-2-méthylbenzène",
				"cyclopentène",
				"éthanal",
				"1,4-diméthylbenzène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide propanoïque.png"><br>',
				"acide propanoïque",
				"4-méthylhexan-1-ol",
				"4-méthylpent-2-èn-2-ol",
				"4-oxopent-2-énal",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 2-bromo-3-hydroxy-5-méthyl-4-oxohex-2-énoïque.png"><br>',
				"acide 2-bromo-3-hydroxy-5-méthyl-4-oxohex-2-énoïque",
				"4-oxopent-2-énal",
				"cyclopentane",
				"acide pent-2-énoïque",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 3-méthylbutanoïque.png"><br>',
				"acide 3-méthylbutanoïque",
				"acide 3-formyl-2-oxobutanoïque",
				"1,3-diméthylbenzène",
				"acide propanoïque",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/4-oxopent-2-énal.png"><br>',
				"4-oxopent-2-énal",
				"propan-2-ol",
				"pent-3-èn-2-one",
				"acide 3-formylbutanoïque",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/2,4,6-triméthyloctan-1-ol.png"><br>',
				"2,4,6-triméthyloctan-1-ol",
				"acide 2-bromo-3-hydroxy-5-méthyl-4-oxohex-2-énoïque",
				"3-éthyl-3-méthylpenta-1,4-diène",
				"2-méthyloctan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide pent-2-énoïque.png"><br>',
				"acide pent-2-énoïque",
				"4-méthylpentan-2-ol",
				"1,2-diméthylcyclohex-1-ène",
				"1,2-diméthylbenzène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/éthanol.png"><br>',
				"éthanol",
				"1,2-diméthylcyclohex-1-ène",
				"4-oxopent-2-énal",
				"éthanal",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 3-formylbutanoïque.png"><br>',
				"acide 3-formylbutanoïque",
				"acide 4-chloro-4-formyl-2-hydroxy-3-méthylbutanoïque",
				"acide pent-2-énoïque",
				"cyclopentène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/4-méthylpent-2-èn-2-ol.png"><br>',
				"4-méthylpent-2-èn-2-ol",
				"acide 2-bromo-3-hydroxy-5-méthyl-4-oxohex-2-énoïque",
				"acide 2-éthyl-3-méthyl-4-oxopent-2-énoïque",
				"1-éthyl-3-méthylcyclopentane",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/acide 4-chloro-4-formyl-2-hydroxy-3-méthylbutanoïque.png"><br>',
				"acide 4-chloro-4-formyl-2-hydroxy-3-méthylbutanoïque",
				"pent-3-èn-2-one",
				"1-chloro-3-méthylbenzène",
				"3-éthyl-3-méthylpenta-1,4-diène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/1,4-diméthylbenzène.png"><br>',
				"1,4-diméthylbenzène",
				"1,2-diméthylcyclohex-1-ène",
				"3-éthyl-3-méthylpenta-1,4-diène",
				"4-méthylhexan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/4-méthylpentan-2-ol.png"><br>',
				"4-méthylpentan-2-ol",
				"4-méthylpent-2-èn-2-ol",
				"2-chloropentane",
				"4-méthyloctan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/cyclopentane.png"><br>',
				"cyclopentane",
				"acide 3-formylbutanoïque",
				"3-méthylbutanal",
				"1-éthyl-3-méthylcyclopentane",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/propan-2-ol.png"><br>',
				"propan-2-ol",
				"4-méthylpent-2-èn-2-ol",
				"3-méthylbutanal",
				"3-éthyl-3-méthylpenta-1,4-diène",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/2-méthylpropan-2-ol.png"><br>',
				"2-méthylpropan-2-ol",
				"3-éthyl-3-méthylpenta-1,4-diène",
				"acide 2-éthyl-3-méthyl-4-oxopent-2-énoïque",
				"propan-2-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/1-chloro-3-méthylbenzène.png"><br>',
				"1-chloro-3-méthylbenzène",
				"acide 4-chloro-4-formyl-2-hydroxy-3-méthylbutanoïque",
				"4-méthylpentan-2-ol",
				"2-méthyloctan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
		'<img class="img_400x400_'+thisDeviceType+'" src="img/abdo 2-mathin-3-adminoïque.png"><br>',
				"abdo 2-mathin-3-adminoïque",
				"admino 2-mathin-3-abdoïque",
				"4-méthylpentan-2-ol",
				"2-méthyloctan-1-ol",
				"Nommer la molécule suivante selon les règles de Nomenclature IUPAC:",
	],
	/* --- game 2 --- */
		[




		],

	]
