	var QCMS = [
		/* --- game 1 --- */
		[
		// startsOf :
		"le liquide où se baigne les organites cellulaires.",
			"Le cytosol",
			"Le cytoplasme",
			"Le Noyau",
			"Le réticulum endoplasmique",
			"",
		"l’ensemble du cytosol et des organites cellulaires.",
			"Le cytoplasme",
			"Le cytosol",
			"La membrane plasmique",
			"L’appareil de Golgi",
			"",
		"Entouré d’une membrane nucléaire. Renferme le matériel génétique sous forme d’ADN.",
			"Le Noyau",
			"La cellule",
			"La vacuole",
			"le pore nucléaire",
			"",
		"Un organite cellulaire polymorphe constitué d’un ou plusieurs dictyosomes.",
			"L’appareil de Golgi",
			"La cellule",
			"La membrane plasmique",
			"Le cytosol",
			"",
		"l'unité structurale, fonctionnelle et reproductrice constituant tout ou partie d'un être vivant.",
			"La cellule",
			"La membrane plasmique",
			"L’appareil de Golgi",
			"Le Noyau",
			"",
		"un réseau de membranes parallèles reliées et formant des cavités.",
			"Le réticulum endoplasmique",
			"La membrane plasmique",
			"le pore nucléaire",
			"Les endosomes",
			"",
		"Il s’agit d’une sécrétion/élimination de molécules présentes dans la cellule.",
			"L’exocytose",
			"Le cytoplasme",
			"L’appareil de Golgi",
			"L’enveloppe nucléaire",
			"",
		'Processus par lequel une cellule absorbe des particules ou des solutés en les englobant dans des vésicules par invagination de la membrane plasmique',
			"L’endocytose",
			"L’anabolisme",
			"Le catabolisme",
			"",
			"",
		'une phase de synthèse, dans laquelle les précurseurs simples sont, grâce à l’énergie accumulée, transformés en macromolécules spécifiques',
			"L’anabolisme",
			"Le catabolisme",
			"L’endocytose",
			"",
			"",
		"des molécules complexes: glucides, lipides, protéines sont décomposées en éléments organiques",
			"Le catabolisme",
			"L’endocytose",
			"L’anabolisme",
			"",
			"",
		'<img style="width:60%" src="img/im1.png"><br>',
			"Végétale",
			"Animale",
			"",
			"",
			'Schéma d’une cellule :',
		"Présent chez les Eucaryotes et les procaryotes, dont la fonction de délimite le contenu de la cellule et contrôle les échanges entre l’intérieur et l’extérieur de la cellule.",
			"La membrane plasmique",
			"Les mitochondries",
			"Les ribosomes",
			"La paroi cellulosique",
			"",
		"un structure complexe en « panier de basket » et de symétrie d’ordre 8.",
			"le pore nucléaire",
			"Le cytoplasme",
			"Le Noyau",
			"Le réticulum endoplasmique",
			"",
		"Empilement de sacs membraneux aplatis. La fonction principale est de modifier, de trier et de concentrer les protéines synthétisées par les ribosomes.",
			"L’appareil de Golgi",
			"La paroi cellulosique",
			"Le système endomembranaire",
			"L’enveloppe nucléaire",
			"",
		"des organites en forme de bâtonnets possédant deux membranes (externe et interne).",
			"Les mitochondries",
			"Les ribosomes",
			"Les lysosomes",
			"Les endosomes",
			"",
		"des petites structures constituées de deux sous-unités d’ARN liées ensemble.",
			"Les ribosomes",
			"Les lysosomes",
			"Les endosomes",
			"Les mitochondries",
			"",
		"vésicules closes qui constituent pour la cellule un centre de stockage des enzymes lytiques et un lieu d'élimination des déchets.",
			"Les lysosomes",
			"Les ribosomes",
			"Les mitochondries",
			"Les endosomes",
			"",
		"un compartiment membranaire très hétérogène sur le plan morphologique.",
			"Les endosomes",
			"Les ribosomes",
			"Les lysosomes",
			"Les endosomes",
			"",
		"Regroupe un ensemble de polymères fibreux et de protéines.",
			"le cytosquelette",
			"La paroi cellulosique",
			"La vacuole",
			"Le cytoplasme",
			"",
		"Doublant la membrane plasmique, confère une résistance mécanique à la cellule et limite les mouvements d’eau vers le cytoplasme, liés à la pression osmotique intracellulaire.",
			"La paroi cellulosique",
			"Le système endomembranaire",
			"La vacuole",
			"L’appareil de Golgi",
			"",
		"Une cavité limitée par une membrane simple, contenant une solution d’ions et de molécules organiques.",
			"La vacuole",
			"Le cytosol",
			"Le cytoplasme",
			"Le réticulum endoplasmique",
			"",
		"est présent uniquement dans les cellules eucaryotes. C’est un système complexe fait de plusieurs cavités, de vésicules et de canalicules.",
			"Le système endomembranaire",
			"La paroi cellulosique",
			"La vacuole",
			"L’appareil de Golgi",
			"",
		"est composée d’une double membrane (externe et interne) dont les deux faces sont en contact avec des filaments intermédiaires, l’enveloppe nucléaire est aussi un site de stockage du Ca2<sup>+</sup>.",
			"L’enveloppe nucléaire",
			"L’appareil de Golgi",
			"La paroi cellulosique",
			"Le système endomembranaire",
			"",
		// endsOf   :
	],
	/* --- game 2 --- */
		[
		],
	];
 